// Openapi Generator last run: : 2025-06-19T10:49:19.561348
import 'package:main_computer/src/kernel.dart';
import 'package:openapi_generator_annotations/openapi_generator_annotations.dart';
import 'package:space_traders/api.dart';

@Openapi(
  inputSpec: RemoteSpec(path: "https://spacetraders.io/SpaceTraders.json"),
  generatorName: Generator.dart,
  outputDirectory: "space_traders_api",
  additionalProperties: AdditionalProperties(
    pubName: "space_traders",
    pubDescription: "Autogenerated code to interact with the SpaceTraders API",
  ),
  skipIfSpecIsUnchanged: true,
)
class SpaceTradersApiGenerator {}

KernelService getExtraShipCommunicationService() {
  return KernelService<ApiClient>(
    name: "Extra-ship Communications",
    start: (context) async {
      final client = ApiClient(
        authentication: HttpBearerAuth()..accessToken = "TODO",
      );

      final myAgent = await AgentsApi(client).getMyAgent();
      if (myAgent == null) {
        throw StateError("Unable to fetch agent informations.");
      }

      print("Hello ${myAgent.data.symbol}!");

      context.expose(client);

      return client;
    },
    stop: (client) => client.client.close(),
  );
}
