// Openapi Generator last run: : 2025-06-19T10:49:19.561348
import 'package:openapi_generator_annotations/openapi_generator_annotations.dart';

@Openapi(
  inputSpec: RemoteSpec(path: "https://spacetraders.io/SpaceTraders.json"),
  generatorName: Generator.dart,
  outputDirectory: "space_traders_api",
  additionalProperties: AdditionalProperties(
    pubName: "space_traders",
    pubDescription: "Autogenerated code to interact with the SpaceTraders API",
  ),
  skipIfSpecIsUnchanged: true,
)
class SpaceTradersApiGenerator {}
