name: main_computer
description: The main component handling all agents management.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
resolution: workspace

dependencies:
  args: ^2.5.0
  openapi_generator_annotations: ^6.1.0
  space_traders:
    path: ./space_traders_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  openapi_generator: ^6.1.0
  build_runner: ^2.4.15
